[tool.poetry]
name = "symmer"
version = "0.0.5"
description = ""
authors = ["AlexisRalli <rallilex@hotmail.co.uk>", "TimWeaving <weaving.timothy@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
openfermion = "^1.3.0"
cached-property = "^1.5.2"
qiskit = "^0.44.0"
pydocstyle = "^6.1.1"
isort = "^5.10.1"
black = "^22.1.0"
flake8 = "^4.0.1"
ncon = "^1.0.0"
opt-einsum = "^3.3.0"
pytest = "^7.2.2"
numba = "0.58.1"
quimb = "^1.5.1"
ray = "^2.6.3"
sphinx-design = "^0.5.0"
myst-nb = "^0.17.2"
sphinx-copybutton = "^0.5.2"
py3dmol = "^2.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
# line-length = 99 # override black's default line-length
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"
